<?php

namespace AppBundle\Repository;

/**
 * SuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviRepository extends \Doctrine\ORM\EntityRepository
{
}
