# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  upload.annotation_reader:
    class: Grafikat\UploadBundle\Annotation\UploadAnnotationReader
    arguments: ["@annotations.reader"]

  upload.handler:
    class: Grafikat\UploadBundle\Handler\UploadHandler
  upload.subscriber:
    class: Grafikat\UploadBundle\Listener\UploadSubscriber
    arguments: ["@upload.annotation_reader", "@upload.handler"]
    tags:
      - { name: doctrine.event_subscriber, connection: default}
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

  security.acl.permission.map:
    class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap


# optionally use a custom MaskBuilder
#parameters:
   # sonata.admin.security.mask.builder.class: Sonata\AdminBundle\Security\Acl\Permission\MaskBuilder

